/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

/* Converter */
export const FETCH_RATES_REQUEST = 'FETCH_RATES_REQUEST';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_FAILURE = 'FETCH_RATES_FAILURE';

export const SAVE_CONVERSION_REQUEST = 'SAVE_CONVERSION_REQUEST';
export const SAVE_CONVERSION_SUCCESS = 'SAVE_CONVERSION_SUCCESS';
export const SAVE_CONVERSION_FAILURE = 'SAVE_CONVERSION_FAILURE';
/* Converter */

/* History */
export const FETCH_CONVERSIONS_REQUEST = 'FETCH_CONVERSIONS_REQUEST';
export const FETCH_CONVERSIONS_SUCCESS = 'FETCH_CONVERSIONS_SUCCESS';
export const FETCH_CONVERSIONS_FAILURE = 'FETCH_CONVERSIONS_FAILURE';
/* History */
